language: csharp
solution: InstagramAPI.sln
dotnet: 1.0.0-preview2-003121
sudo: required
os: linux
dist: trusty

script:
  # dotnet info
  - dotnet --info
  # Run dotnet new 
  - dotnet restore
  - cd InstagramAPI
  - dotnet --verbose build
  - cd ../InstagramAPI.Tests
  - dotnet --verbose build
  - dotnet --verbose test
  