version: 1.2.1 ({build})
os: Visual Studio 2015
platform: Any CPU
configuration: Release

branches:
  only:
    - release
    - master
skip_commits:
  message: /skip ci/      # Regex for matching commit message

skip_tags: true

build:
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages
  include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifacts
  
build_script:
  - ps: dotnet --info
  - ps: dotnet restore
  - ps: cd InstaSharper
  - ps: dotnet --verbose build
  - ps: dotnet --verbose pack -o ../nugetpack -c release
  - ps: cd ../InstaSharper.Tests
  - ps: dotnet restore
  - ps: dotnet --verbose build
  - ps: dotnet --verbose test -parallel none
  - ps: cd ..

assembly_info:
  patch: true
  file: project.json
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

environment:
  instaapiuserpassword:
    secure: 7eAl+O5i5BxXWexd26z+wg==
    
artifacts:

  - path: InstaSharper\bin\$(configuration)\netstandard1.6\*.dll
    name: dlls
    
  - path: '**\*.nupkg'
  
deploy:
  - provider: GitHub
    auth_token:
      secure: FE6k4kAwz++t3+H7UvZkUELVZsx8DIjSOM1R3ZVT7YgqwQXuMKFQpDM5HmQobF22
    artifact: /.*\.nupkg/, dlls
    draft: false
    prerelease: false
    on:
      branch: release
      platform: Any CPU
      configuration: Release
  - provider: NuGet
    api_key:
        secure: At3FDhivtW6bQz/WXdwE6RzuFeouCMag3htqBE/1uuTJnFmHB8hU9gCy31ORFWtS
    artifact: /.*\.nupkg/
    on:
      branch: release
      platform: Any CPU
      configuration: Release
test: off
